# this script based off of https://github.com/tolbertam/mocha-appveyor-reporter/blob/master/appveyor.yml
# python settings based off of https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

environment:
  matrix:
    # we need to specify py3 because py2 is default (AREPL does not support py2)
    - PYTHON: "C:\\Python35-x64" # this version of python is pre-installed on appveyor
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "64"

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node ''
  - npm install

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: off

test_script:
  - npm run appveyorTest

cache:
  - node_modules -> package.json

notifications:
  - provider: Email
    to:
      - almenon214@gmail.com
    on_build_success: false